ALTER TABLE users
ADD COLUMN last_login TIMESTAMP(6) WITH TIME ZONE,
ADD COLUMN login_attempts INTEGER DEFAULT 0,
ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN account_non_expired BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN account_non_locked BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN dob DATE,
ADD COLUMN telephone VARCHAR(50),
DROP COLUMN password;

CREATE TABLE credentials (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
password VARCHAR(255) NOT NULL,
user_id BIGINT NOT NULL,
created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
last_modified_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uq_credentials_user_id UNIQUE (user_id),
CONSTRAINT fk_credentials_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE confirmations (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
conf_key VARCHAR(255) NOT NULL,
user_id BIGINT NOT NULL,
created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
last_modified_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uq_confirmations_user_id UNIQUE (user_id),
CONSTRAINT uq_confirmations_key UNIQUE (conf_key),
CONSTRAINT fk_confirmations_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_credentials_user_id ON credentials(user_id);
CREATE INDEX idx_confirmations_user_id ON confirmations(user_id);
