INSERT INTO categories (name) VALUES ('Mens T-Shirts');
INSERT INTO categories (name) VALUES ('Smartphones');
INSERT INTO categories (name) VALUES ('Apparel');
INSERT INTO categories (name) VALUES ('Home Appliances');
INSERT INTO categories (name) VALUES ('Toys');
INSERT INTO categories (name) VALUES ('Furniture');
INSERT INTO categories (name) VALUES ('Books');
INSERT INTO categories (name) VALUES ('Sports Equipment');
INSERT INTO categories (name) VALUES ('Beauty Products');
INSERT INTO categories (name) VALUES ('Automotive');
INSERT INTO categories (name) VALUES ('Outdoor Gear');
INSERT INTO categories (name) VALUES ('Electronics');
INSERT INTO categories (name) VALUES ('Kitchen Appliances');
INSERT INTO categories (name) VALUES ('Baby Products');
INSERT INTO categories (name) VALUES ('Health & Fitness');
INSERT INTO categories (name) VALUES ('Garden & Outdoor');
INSERT INTO categories (name) VALUES ('Pet Supplies');
INSERT INTO categories (name) VALUES ('Office Supplies');
INSERT INTO categories (name) VALUES ('Jewelry & Watches');
INSERT INTO categories (name) VALUES ('Travel & Luggage');
INSERT INTO categories (name) VALUES ('Musical Instruments');
INSERT INTO categories (name) VALUES ('Crafts & Hobbies');
INSERT INTO categories (name) VALUES ('Collectibles & Memorabilia');
INSERT INTO categories (name) VALUES ('Art & Decor');
INSERT INTO categories (name) VALUES ('Food & Beverages');
INSERT INTO categories (name) VALUES ('Stationery & Gift Wrapping');
INSERT INTO categories (name) VALUES ('Electrical & Lighting');
INSERT INTO categories (name) VALUES ('DIY & Tools');
INSERT INTO categories (name) VALUES ('Party Supplies');
INSERT INTO categories (name) VALUES ('Educational Toys');
